package com.shamala.dailylight

/**
 * The words the widget draws from.
 *
 * Both pools are original writing (no third-party quotations), so the app
 * carries no attribution obligations. Add, remove or reword freely — the
 * rotation logic in [DailyContent] adapts to whatever length these are.
 */
object Words {

    /** First person, present tense. Something to stand on, not to perform. */
    val affirmations = listOf(
        "Today has not been lived yet. It is entirely mine.",
        "I begin again, and beginning again is not starting over.",
        "I am allowed to move at the pace that keeps me honest.",
        "What I do steadily matters more than what I do dramatically.",
        "I can hold high standards and be kind to myself in the same breath.",
        "I don't need to feel ready to begin. I only need to begin.",
        "My worth is not a score. It is not up for recalculation today.",
        "I trust the version of me that shows up before the doubt does.",
        "I have carried harder mornings than this one.",
        "Small and consistent is a real strategy, not a consolation prize.",
        "I am permitted to be a beginner at something today.",
        "The work will meet me where I am. It always has.",
        "I can be uncertain and still be capable.",
        "I choose depth over speed today.",
        "Nothing about yesterday is required to repeat itself.",
        "I am becoming someone I would have admired a year ago.",
        "Rest is part of the work, not a break from it.",
        "I can do one difficult thing before the day gets loud.",
        "My attention is the most valuable thing I own. I spend it deliberately.",
        "I am not behind. I am on my own timeline.",
        "Clarity comes from moving, not from waiting to feel clear.",
        "I forgive myself quickly and get back to the thing.",
        "I am someone who finishes.",
        "Today I will be curious before I am critical.",
        "I can change my mind. That is a sign of thinking, not of weakness.",
        "I am building something that does not need to be visible yet.",
        "What I practice, I become.",
        "I do not have to earn the right to a good day.",
        "The hard part is temporary. The skill is permanent.",
        "I bring calm into the room I walk into.",
        "I can be tired and still be strong.",
        "I let today be enough on its own terms.",
        "I meet difficulty with attention instead of alarm.",
        "I am the same person on the quiet days as on the good ones.",
        "I choose the honest effort over the impressive shortcut.",
        "There is time. There is more time than I fear.",
        "I keep my promises to myself first.",
        "I am learning, which means I am supposed to be uncomfortable sometimes.",
        "My best is a moving thing, and today's version counts.",
        "I can start in the middle. Most good things do.",
        "I notice what is going well, on purpose.",
        "I will not trade my peace for someone else's urgency.",
        "I can hold two hard things at once and still move.",
        "I am not the mistake. I am the one who corrects it.",
        "Today I choose the long game.",
        "I get to decide what kind of morning this becomes.",
        "I do the next right thing, then the one after that.",
        "I am steadier than I was, and I will be steadier still.",
        "I let go of the outcome and keep the effort.",
        "Enough is a decision, not a threshold I reach.",
        "I show up for the person I am becoming.",
        "I am allowed to want more and be grateful now.",
        "The quiet work counts. It counts most.",
        "I set down what is not mine to carry today.",
        "I am capable of sustained, unglamorous effort.",
        "I choose to be present for the ordinary parts.",
        "I can ask for help without it costing me anything.",
        "My progress does not need an audience to be real.",
        "I return to what matters as many times as it takes.",
        "I am not in a race. I am in a practice.",
        "I trust my preparation.",
        "Today I protect my focus like it belongs to someone I love.",
        "I can be gentle and still be relentless.",
        "The door I am looking for opens from the inside.",
        "I will be proud of how I handled today, not just what I got done.",
        "I am safe to try, and safe to be imperfect at it.",
        "I put down the comparison and pick up the work.",
        "Momentum starts with something small and slightly boring.",
        "I let this morning be simple.",
        "I have everything I need to take the first step.",
        "I am consistent, and consistency compounds.",
        "I choose to finish what I start today, however small.",
        "I make room for joy without waiting to deserve it.",
        "I am the kind of person who keeps going.",
        "Today I trade worry for one concrete action.",
        "I honour my energy and work with it, not against it.",
        "My life is not on hold. It is happening now, in this.",
        "I can be new at this and still be good at it eventually.",
        "I am building patience the way I build anything — by practising.",
        "I begin the day on my own terms.",
        "I do not need permission to take myself seriously.",
        "I let today be a clean page, not a continuation of the argument.",
        "I am resourceful. I have proven that repeatedly.",
        "Something good is being assembled quietly.",
        "I choose the effort I can sustain for a year.",
        "I return to my breath, and then to my work.",
        "Today counts, whether or not anyone notices."
    )

    /** A short reflection to sit with. Also original. */
    val thoughts = listOf(
        "A day is not made or lost in its first hour, but that hour decides how you meet the rest of it.",
        "Discipline is mostly a matter of making the good choice slightly easier than the bad one.",
        "You do not need more motivation. You need a smaller first step.",
        "The things that change a life are almost always boring on the day you do them.",
        "Attention is the rarest form of generosity, including toward yourself.",
        "Progress hides in the days that felt like nothing happened.",
        "Doing something imperfectly today beats doing it perfectly in an imagined future.",
        "Comparison measures your inside against someone else's outside. It was never a fair scale.",
        "Momentum is built, not found. It starts with the smallest honest act.",
        "You are allowed to change the plan. You are not required to abandon the goal.",
        "Difficulty is often just unfamiliarity wearing a heavier coat.",
        "The mind quiets when the hands begin.",
        "Everything you are good at was once something you were bad at in public.",
        "The cost of starting is always smaller than the cost of another day of not starting.",
        "Consistency is not intensity repeated. It is moderation sustained.",
        "You cannot think your way into clarity about a thing you have not yet tried.",
        "Rest that you take deliberately restores you. Rest you take guiltily does not.",
        "A goal is a direction, not a debt.",
        "Most overwhelm is several small tasks standing very close together.",
        "The version of you that finishes is built by the version that keeps beginning.",
        "You will not always feel like it. Feeling like it was never the requirement.",
        "Time spent learning slowly is not time lost. It is the only kind that holds.",
        "Half of confidence is simply a record of having done the thing before.",
        "Say no to something today so that your yes still means something.",
        "The distance between where you are and where you want to be is mostly made of ordinary Tuesdays.",
        "Do the hard thing while it is still small.",
        "Curiosity outperforms discipline on the days discipline is unavailable.",
        "Every skill has an ugly middle. Nobody photographs it.",
        "You are not required to be interesting today. Only present.",
        "The point of a plan is to free your mind, not to bind your day.",
        "Being kind to yourself is a performance strategy, not a soft option.",
        "One finished small thing is worth more than three brilliant unfinished ones.",
        "The mind wants novelty. The work wants repetition. Give the work its way.",
        "You cannot control the outcome, but you can make it more likely, repeatedly.",
        "It is a good sign when a task feels slightly too big. That is the size of growth.",
        "Notice what you did do. The list is longer than it feels.",
        "Nobody is coming to give you permission. That is the bad news and the freedom.",
        "The people you admire were also uncertain. They just kept working through it.",
        "The morning is the only part of the day nobody else has claimed yet.",
        "Interruptions cost more than the minutes they take. Guard the block, not the hour.",
        "A hard conversation is usually shorter than the week you spend avoiding it.",
        "Ambition without rest is just a slower way of stopping.",
        "You learn the most in the moment just after you were wrong.",
        "Simplicity is what you arrive at, not what you begin with.",
        "Effort is renewable. Guilt is not. Spend the renewable one.",
        "The story you tell yourself in the first ten minutes tends to be the story of the day.",
        "Standards are useful. Perfectionism is a standard that has stopped being useful.",
        "Doing it badly is a legitimate stage. It is not a verdict.",
        "You don't rise to your ambitions. You settle at the level of your habits.",
        "Small kindnesses to your future self: a made bed, a closed tab, a written next step.",
        "Not everything worth doing will feel urgent. Almost nothing important does.",
        "The best time to protect tomorrow morning is tonight.",
        "You can be behind on a schedule and still be exactly on time for your life.",
        "Growth feels like inadequacy from the inside. That is not evidence against it.",
        "The thing you keep circling back to is probably the thing.",
        "Finish the sentence, then the paragraph. The book takes care of itself.",
        "A quiet day well spent is not a wasted one.",
        "Patience is not passive. It is effort with a longer horizon.",
        "You are allowed to take up space in your own day.",
        "Clarity is a side effect of action, never a prerequisite for it.",
        "What feels like laziness is often just an unclear next step.",
        "Enthusiasm starts projects. Systems finish them.",
        "Ask what you would do if you were not afraid, then do a smaller version of that.",
        "The days you least want to show up are the ones that count double.",
        "Your standards can stay high while your self-talk gets softer.",
        "Whatever you practise repeatedly, you are getting better at — including worry.",
        "Choose one thing today that your future self will thank you for.",
        "There is no finish line where you finally feel ready. There is only the next honest attempt.",
        "You have been the person who figured it out before.",
        "Do less, but finish it.",
        "The best system is the one you will still be doing in six months.",
        "Some days the win is simply that you did not quit.",
        "Attention given fully to one thing feels like more time, not less.",
        "You cannot pour a foundation and see a building on the same day.",
        "Being tired is information, not a character flaw.",
        "The gap between knowing and doing is closed only by starting.",
        "Let today be the day you stop rehearsing and start doing a rough draft.",
        "Anything worth building will look unimpressive for longer than you expect.",
        "The point is not to have a perfect day. It is to have an honest one.",
        "You are further along than the version of you who first wanted this.",
        "What you do on the unremarkable days is what you are actually building.",
        "Give the first hour to what matters and the rest of the day forgives a lot.",
        "It is a good life if most days you did the work and were kind about it.",
        "Begin. The rest is negotiable."
    )
}
