package com.shamala.dailylight

/**
 * The words the widget draws from.
 *
 * Both pools are original writing (no third-party quotations), so the app
 * carries no attribution obligations. Add, remove or reword freely — the
 * rotation logic in [DailyContent] adapts to whatever length these are.
 */
object Words {

    /** First person, present tense. Something to stand on, not to perform. */
    val affirmations = listOf(
        "Today has not been lived yet. It is entirely mine.",
        "I begin again, and beginning again is not starting over.",
        "I am allowed to move at the pace that keeps me honest.",
        "What I do steadily matters more than what I do dramatically.",
        "I can hold high standards and be kind to myself in the same breath.",
        "I don't need to feel ready to begin. I only need to begin.",
        "My worth is not a score. It is not up for recalculation today.",
        "I trust the version of me that shows up before the doubt does.",
        "I have carried harder mornings than this one.",
        "Small and consistent is a real strategy, not a consolation prize.",
        "I am permitted to be a beginner at something today.",
        "The work will meet me where I am. It always has.",
        "I can be uncertain and still be capable.",
        "I choose depth over speed today.",
        "Nothing about yesterday is required to repeat itself.",
        "I am becoming someone I would have admired a year ago.",
        "Rest is part of the work, not a break from it.",
        "I can do one difficult thing before the day gets loud.",
        "My attention is the most valuable thing I own. I spend it deliberately.",
        "I am not behind. I am on my own timeline.",
        "Clarity comes from moving, not from waiting to feel clear.",
        "I forgive myself quickly and get back to the thing.",
        "I am someone who finishes.",
        "Today I will be curious before I am critical.",
        "I can change my mind. That is a sign of thinking, not of weakness.",
        "I am building something that does not need to be visible yet.",
        "What I practice, I become.",
        "I do not have to earn the right to a good day.",
        "The hard part is temporary. The skill is permanent.",
        "I bring calm into the room I walk into.",
        "I can be tired and still be strong.",
        "I let today be enough on its own terms.",
        "I meet difficulty with attention instead of alarm.",
        "I am the same person on the quiet days as on the good ones.",
        "I choose the honest effort over the impressive shortcut.",
        "There is time. There is more time than I fear.",
        "I keep my promises to myself first.",
        "I am learning, which means I am supposed to be uncomfortable sometimes.",
        "My best is a moving thing, and today's version counts.",
        "I can start in the middle. Most good things do.",
        "I notice what is going well, on purpose.",
        "I will not trade my peace for someone else's urgency.",
        "I can hold two hard things at once and still move.",
        "I am not the mistake. I am the one who corrects it.",
        "Today I choose the long game.",
        "I get to decide what kind of morning this becomes.",
        "I do the next right thing, then the one after that.",
        "I am steadier than I was, and I will be steadier still.",
        "I let go of the outcome and keep the effort.",
        "Enough is a decision, not a threshold I reach.",
        "I show up for the person I am becoming.",
        "I am allowed to want more and be grateful now.",
        "The quiet work counts. It counts most.",
        "I set down what is not mine to carry today.",
        "I am capable of sustained, unglamorous effort.",
        "I choose to be present for the ordinary parts.",
        "I can ask for help without it costing me anything.",
        "My progress does not need an audience to be real.",
        "I return to what matters as many times as it takes.",
        "I am not in a race. I am in a practice.",
        "I trust my preparation.",
        "Today I protect my focus like it belongs to someone I love.",
        "I can be gentle and still be relentless.",
        "The door I am looking for opens from the inside.",
        "I will be proud of how I handled today, not just what I got done.",
        "I am safe to try, and safe to be imperfect at it.",
        "I put down the comparison and pick up the work.",
        "Momentum starts with something small and slightly boring.",
        "I let this morning be simple.",
        "I have everything I need to take the first step.",
        "I am consistent, and consistency compounds.",
        "I choose to finish what I start today, however small.",
        "I make room for joy without waiting to deserve it.",
        "I am the kind of person who keeps going.",
        "Today I trade worry for one concrete action.",
        "I honour my energy and work with it, not against it.",
        "My life is not on hold. It is happening now, in this.",
        "I can be new at this and still be good at it eventually.",
        "I am building patience the way I build anything — by practising.",
        "I begin the day on my own terms.",
        "I do not need permission to take myself seriously.",
        "I let today be a clean page, not a continuation of the argument.",
        "I am resourceful. I have proven that repeatedly.",
        "Something good is being assembled quietly.",
        "I choose the effort I can sustain for a year.",
        "I return to my breath, and then to my work.",
        "Today counts, whether or not anyone notices."
    )

    /** A short reflection to sit with. Also original. */
    val thoughts = listOf(
        "A day is not made or lost in its first hour, but that hour decides how you meet the rest of it.",
        "Discipline is mostly a matter of making the good choice slightly easier than the bad one.",
        "You do not need more motivation. You need a smaller first step.",
        "The things that change a life are almost always boring on the day you do them.",
        "Attention is the rarest form of generosity, including toward yourself.",
        "Progress hides in the days that felt like nothing happened.",
        "Doing something imperfectly today beats doing it perfectly in an imagined future.",
        "Comparison measures your inside against someone else's outside. It was never a fair scale.",
        "Momentum is built, not found. It starts with the smallest honest act.",
        "You are allowed to change the plan. You are not required to abandon the goal.",
        "Difficulty is often just unfamiliarity wearing a heavier coat.",
        "The mind quiets when the hands begin.",
        "Everything you are good at was once something you were bad at in public.",
        "The cost of starting is always smaller than the cost of another day of not starting.",
        "Consistency is not intensity repeated. It is moderation sustained.",
        "You cannot think your way into clarity about a thing you have not yet tried.",
        "Rest that you take deliberately restores you. Rest you take guiltily does not.",
        "A goal is a direction, not a debt.",
        "Most overwhelm is several small tasks standing very close together.",
        "The version of you that finishes is built by the version that keeps beginning.",
        "You will not always feel like it. Feeling like it was never the requirement.",
        "Time spent learning slowly is not time lost. It is the only kind that holds.",
        "Half of confidence is simply a record of having done the thing before.",
        "Say no to something today so that your yes still means something.",
        "The distance between where you are and where you want to be is mostly made of ordinary Tuesdays.",
        "Do the hard thing while it is still small.",
        "Curiosity outperforms discipline on the days discipline is unavailable.",
        "Every skill has an ugly middle. Nobody photographs it.",
        "You are not required to be interesting today. Only present.",
        "The point of a plan is to free your mind, not to bind your day.",
        "Being kind to yourself is a performance strategy, not a soft option.",
        "One finished small thing is worth more than three brilliant unfinished ones.",
        "The mind wants novelty. The work wants repetition. Give the work its way.",
        "You cannot control the outcome, but you can make it more likely, repeatedly.",
        "It is a good sign when a task feels slightly too big. That is the size of growth.",
        "Notice what you did do. The list is longer than it feels.",
        "Nobody is coming to give you permission. That is the bad news and the freedom.",
        "The people you admire were also uncertain. They just kept working through it.",
        "The morning is the only part of the day nobody else has claimed yet.",
        "Interruptions cost more than the minutes they take. Guard the block, not the hour.",
        "A hard conversation is usually shorter than the week you spend avoiding it.",
        "Ambition without rest is just a slower way of stopping.",
        "You learn the most in the moment just after you were wrong.",
        "Simplicity is what you arrive at, not what you begin with.",
        "Effort is renewable. Guilt is not. Spend the renewable one.",
        "The story you tell yourself in the first ten minutes tends to be the story of the day.",
        "Standards are useful. Perfectionism is a standard that has stopped being useful.",
        "Doing it badly is a legitimate stage. It is not a verdict.",
        "You don't rise to your ambitions. You settle at the level of your habits.",
        "Small kindnesses to your future self: a made bed, a closed tab, a written next step.",
        "Not everything worth doing will feel urgent. Almost nothing important does.",
        "The best time to protect tomorrow morning is tonight.",
        "You can be behind on a schedule and still be exactly on time for your life.",
        "Growth feels like inadequacy from the inside. That is not evidence against it.",
        "The thing you keep circling back to is probably the thing.",
        "Finish the sentence, then the paragraph. The book takes care of itself.",
        "A quiet day well spent is not a wasted one.",
        "Patience is not passive. It is effort with a longer horizon.",
        "You are allowed to take up space in your own day.",
        "Clarity is a side effect of action, never a prerequisite for it.",
        "What feels like laziness is often just an unclear next step.",
        "Enthusiasm starts projects. Systems finish them.",
        "Ask what you would do if you were not afraid, then do a smaller version of that.",
        "The days you least want to show up are the ones that count double.",
        "Your standards can stay high while your self-talk gets softer.",
        "Whatever you practise repeatedly, you are getting better at — including worry.",
        "Choose one thing today that your future self will thank you for.",
        "There is no finish line where you finally feel ready. There is only the next honest attempt.",
        "You have been the person who figured it out before.",
        "Do less, but finish it.",
        "The best system is the one you will still be doing in six months.",
        "Some days the win is simply that you did not quit.",
        "Attention given fully to one thing feels like more time, not less.",
        "You cannot pour a foundation and see a building on the same day.",
        "Being tired is information, not a character flaw.",
        "The gap between knowing and doing is closed only by starting.",
        "Let today be the day you stop rehearsing and start doing a rough draft.",
        "Anything worth building will look unimpressive for longer than you expect.",
        "The point is not to have a perfect day. It is to have an honest one.",
        "You are further along than the version of you who first wanted this.",
        "What you do on the unremarkable days is what you are actually building.",
        "Give the first hour to what matters and the rest of the day forgives a lot.",
        "It is a good life if most days you did the work and were kind about it.",
        "Begin. The rest is negotiable."
    )

    // ---------------------------------------------------------------------
    // Evening voice. Shown after the hour set in settings (18:00 by default).
    // Same first-person present tense, but the work of the evening is
    // different: setting down, noticing, and being allowed to stop.
    // ---------------------------------------------------------------------

    val eveningAffirmations = listOf(
        "The day is finished, and so am I. Both are allowed.",
        "I did what today had room for.",
        "I set down what I did not get to. It will keep.",
        "Something went better than I expected today.",
        "I am allowed to stop before everything is done.",
        "I let the unfinished stay unfinished until morning.",
        "I was here for today, and that counted.",
        "I forgive myself for the parts that went badly.",
        "Rest is not a reward I have to earn first.",
        "I release the conversation I keep replaying.",
        "Tomorrow gets tomorrow's strength. Tonight I only need tonight's.",
        "I am not behind. I am finished for today.",
        "I close the day gently rather than abandoning it.",
        "What I carried today, I can put down now.",
        "I did not have to be at my best for the day to be worth it.",
        "I let go of the version of today I had planned.",
        "There was more good in today than I noticed while it was happening.",
        "I am allowed to be proud of something small.",
        "The work will still be there. So will I.",
        "I choose peace over one more thing.",
        "I stop now, not because it is done, but because it is evening.",
        "I am softer with myself at night than the day was with me.",
        "Whatever I did not solve today does not have to be solved tonight.",
        "I let the day be ordinary. Most of them are, and that is fine.",
        "I take the lesson and leave the shame.",
        "I have permission to be tired.",
        "I did more than I am giving myself credit for.",
        "I let tomorrow be a separate day, not a continuation of this one.",
        "The house is quiet and nothing is required of me.",
        "I close the loops I can and let the rest be open.",
        "I am not the sum of today's productivity.",
        "I keep what was good and let the rest wash out.",
        "I turn the volume down on the part of me that keeps score.",
        "I am allowed to have done enough.",
        "The day asked a lot. I answered as well as I could.",
        "I let the tightness in my shoulders go before I let the thoughts go.",
        "I did not get it all right, and the day still ends kindly.",
        "I trade the running commentary for quiet.",
        "I stop rehearsing tomorrow. Tomorrow does not need rehearsing.",
        "I let myself be off duty.",
        "There is nothing I need to fix in the next ten minutes.",
        "I was patient at least once today, and that took something.",
        "I let the day close without a verdict on it.",
        "Whatever happens tomorrow, tonight I rest.",
        "I did the thing I did not feel like doing. That still counts tonight.",
        "I am not late. I am simply still going.",
        "Tomorrow I begin again, and beginning again is enough.",
        "I let the noise of the day settle like sediment.",
        "Nothing about tonight has to be productive.",
        "I am safe, I am finished, and I can stop now.",
        "I put the day away carefully rather than dropping it.",
        "I let the hardest hour of today be over.",
        "The next thing I have to do is nothing.",
        "I let today be a day I lived rather than a day I completed.",
        "I made it here, and here is a fine place to stop.",
        "Sleep is the work now."
    )

    val eveningThoughts = listOf(
        "The day does not need a verdict before you are allowed to rest from it.",
        "Most of what felt urgent this morning has quietly stopped mattering.",
        "Unfinished is a normal state for anything worth doing.",
        "You will not remember today's inbox. You may remember how you spoke to someone in it.",
        "The mind replays the one thing that went wrong and skips the nine that went right. That is a bug, not a report.",
        "Tiredness makes everything look worse than it is. Judge tomorrow's problems tomorrow.",
        "Something you did today made tomorrow slightly easier, even if you can't name it.",
        "You are allowed to close a day that did not go to plan without an inquiry.",
        "Rest is what turns effort into progress. Skipping it wastes the effort.",
        "The day was long. That does not mean it was wasted.",
        "You do not have to solve it tonight. You only have to sleep.",
        "Whatever you're still turning over will look different in the morning — it always does.",
        "Setting something down is not the same as giving up on it.",
        "The hours you spent being patient today don't appear on any list, but they cost the most.",
        "Nobody's day goes the way they planned it. They just don't narrate the gap out loud.",
        "Ending well matters more than ending completely.",
        "Guilt at the end of a day is rarely proportional to what actually happened.",
        "The work you did today will still be there tomorrow, in better shape than you think.",
        "Being kind to yourself tonight is what makes you capable tomorrow.",
        "You cannot be behind on a life. There is no schedule you were issued.",
        "A day where you were mostly decent to people is a good day, whatever else it held.",
        "The best thing you can do for tomorrow is stop working on it now.",
        "Some days you build. Some days you just don't lose ground. Both are days.",
        "The thought that keeps coming back is not more true for repeating.",
        "You did not waste the day. You spent it, which is what days are for.",
        "Notice one thing that went right, deliberately. The mind will not do it for you.",
        "The evening is not a deadline you failed to meet.",
        "Whatever you are worried about, you have handled things like it before.",
        "Half of tomorrow's difficulty is tonight's exhaustion talking.",
        "You are permitted to have limits, and to have reached them.",
        "A quiet evening is not an empty one.",
        "The unfinished list is evidence of ambition, not of failure.",
        "Stopping at a good place beats stopping at an exhausted one. Stop earlier tomorrow.",
        "You do not owe anyone an account of how you spent today.",
        "Tomorrow's version of you will be fresher, kinder and better at this. Leave it to them.",
        "You were not put here to clear a queue.",
        "The day ends whether or not you are ready. Let it.",
        "Whatever you learned today, you learned by getting something wrong first.",
        "Enough is a decision you get to make at the end of the day, too.",
        "There is no prize for the person who thought about work the longest.",
        "The people who love you are not keeping score of your output.",
        "Being tired is the body's honest report, not a complaint.",
        "You'll do it better tomorrow because you stopped tonight.",
        "The evening is the one part of the day that asks nothing of you. Let it stay that way.",
        "Everything you are anxious about tonight has a smaller version in daylight.",
        "You showed up. On a lot of days, that is the whole achievement.",
        "The last hour of the day is a bad time to make a judgment about your life.",
        "Put the day down the way you'd put down something fragile — deliberately, not by dropping it.",
        "A good night is the cheapest performance improvement available to you.",
        "Tomorrow you get to begin again, which is the most generous rule there is.",
        "Nothing important will be decided in the next hour. Let the hour be yours.",
        "You made it through a day that you could not fully predict. You do this constantly.",
        "The quiet at the end of the day is earned, not borrowed.",
        "Stop. It is later than the work thinks it is.",
        "Tomorrow is not a test. It's just the next day, and you're good at those.",
        "Goodnight. Today is closed."
    )
}
